name: "CD (Entrega/Delivery Contínua): Main Workflow"

env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            # Runs install
            - name: Run Installation
              run: yarn install
            # Runs linter command
            - name: Run Deploy
              run: yarn deploy:prod            