name: "CI (Integração Contínua): Main Workflow"

permissions:
  pull-requests: write
  contents: write

env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
    GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

on:
    pull_request:
        types: [opened, synchronize]

jobs: 
    linter: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            # Runs install
            - name: Run Installation
              run: yarn install
            # Runs linter command
            - name: Run Linter
              run: yarn lint
    preview:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Run Installation
              run: yarn install
            - name: Run Preview Deployment
              run: yarn deploy:preview